Fix ospfv2 module improperly rendering distance.admin_distance.
ansible-collections/cisco.ios pull request #1029
Opened 2024-02-07 04:36 UTC by round3d

##### SUMMARY

Fixes the ospfv2 distance.admin_distance template. 
Minor changes to qualify the properties in the setval of the template.

Fixes #1028 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ospfv2

##### ADDITIONAL INFORMATION

before:
```paste below

    "rendered": [
        "router ospf 1"
    ]
```
after:
```
    "rendered": [
        "router ospf 1",
        "distance 1 "
    ]

```

2024-02-07 09:16 UTC, KB-perByte commented
Hey @round3d Thank you for your contribution, can you please add a changelog and a unit test case to confirm your changes?
Let us know if you need any help.
Regards

2024-02-07 15:05 UTC, round3d commented
Hi @KB-perByte , 
I can do that with the changelog.

The existing test case test_ios_ospfv2_rendered (and some others that include distance.admin_distance) should already cover it, but the commands list for the assert doesn't include the admin lines that should be rendered.  It includes the distance ospf config but not the distance for admin_distance. That's the cause of some of those checks failing.


https://github.com/ansible-collections/cisco.ios/blob/cefdf849fb395ebca2b49b342a524fa9e4430680/tests/unit/modules/network/ios/test_ios_ospfv2.py#L753-L765

https://github.com/ansible-collections/cisco.ios/blob/cefdf849fb395ebca2b49b342a524fa9e4430680/tests/unit/modules/network/ios/test_ios_ospfv2.py#L915-L950

Sorry if that's not clear.

2024-02-08 09:02 UTC, roverflow requested changes
Please fix the tests and add a changelog as mentioned above

2024-02-08 17:22 UTC, round3d commented
> Please fix the tests and add a changelog as mentioned above

Hi @roverflow , I've done that.  Thanks.

2024-02-09 06:09 UTC, roverflow commented on changelogs/fragments/ospfv2_admin_distance_fix.yml
> +  - ospfv2 - Fixed rendering of admin_distance.
```suggestion
  - ios_ospfv2 - Fix improper rendering of admin_distance attribute.
```

2024-02-09 06:26 UTC, roverflow approved these changes

2024-02-09 06:26 UTC, merged