Integration test fix for ios_user
ansible-collections/cisco.ios pull request #1034
Opened 2024-02-15 14:26 UTC by roverflow

##### SUMMARY
Replaced the hash which was being used to test type 5 secret.

##### ISSUE TYPE
- Test fix

2024-02-15 14:27 UTC, KB-perByte requested changes

2024-02-15 14:27 UTC, KB-perByte commented on changelogs/fragments/ios_user_int_test.yml
> +minor_changes:
this is just a test change!

2024-02-15 14:28 UTC, roverflow commented on changelogs/fragments/ios_user_int_test.yml
> +minor_changes:
Should i just have no changelog??

2024-02-16 08:34 UTC, KB-perByte approved these changes

2024-02-16 08:34 UTC, merged