Added doc changes for logging_global
ansible-collections/cisco.ios pull request #1074
Opened 2024-05-14 09:56 UTC by roverflow

##### SUMMARY
This PR fixes - #1072 

Update documentation - ios_logging_global for severity attribute within buffered.

##### ISSUE TYPE
- Docs Pull Request

2024-05-14 14:39 UTC, KB-perByte commented on plugins/modules/ios_logging_global.py
> +              - Idempotancy is not maintained for this attribute as value not shown in running-config
maybe this behavior is specific to the version we currently test with, let's add integration tests to check this nature, and add a comment there. Incase this fails the test in the future we would know to update the doc and fix the test.

2024-05-22 17:52 UTC, KB-perByte requested changes

2024-05-22 17:52 UTC, KB-perByte commented on tests/integration/targets/ios_logging_global/tests/cli/merged.yaml
> +          - "'logging buffered xml 5099 debugging' in resultdeb['commands']"
assert the after dict to confirm that it impacts idempotency.

2024-05-31 06:25 UTC, NilashishC commented on plugins/modules/ios_logging_global.py
> +              - Idempotancy is not maintained for this attribute for the value debugging
```suggestion
              - Idempotency is not maintained for this attribute for the value 'debugging'
```

2024-05-31 06:25 UTC, NilashishC commented on plugins/modules/ios_logging_global.py
> +                as value not shown in running-config
```suggestion
                since this value is not shown in running-config.
```

2024-05-31 08:48 UTC, KB-perByte approved these changes

2024-05-31 08:51 UTC, merged