IOS_CONFIG - incorrectly claims success when 'Command Rejected'
ansible-collections/cisco.ios pull request #215
Opened 2020-12-10 11:04 UTC by nidebr

##### SUMMARY
Hi all, allow check "Command Reject" on config mode.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

In the current implementation, configuring with "ios_config" not check if command is rejected and ansible still reports "changed", comes back and reports success, and ignores the fact they were rejected.

```
# Before :
# -------------

SWITCH#sh run int gigabitEthernet 1/3
Building configuration...

Current configuration : 378 bytes
!
interface GigabitEthernet1/3
 switchport trunk encapsulation dot1q
 switchport trunk native vlan 4094
 switchport mode trunk
 mtu 9198
 load-interval 30
 media-type rj45
 negotiation auto
 no keepalive
 no lldp transmit
 no lldp receive
 no cdp enable
 spanning-tree portfast network
 spanning-tree bpdufilter enable
end

# Task 

- name: "COMMAND"
  ios_config:
    lines:
      - switchport private-vlan mapping 10 6000
    parents: interface GigabitEthernet1/3
    save_when: modified
  register: output
  ignore_errors: yes

- name: debug
  debug:
    var: output

# Output

PLAY [SW-TEST] **********************************************************************************************************************

TASK [test : COMMAND] ***************************************************************************************************
changed: [SW-TEST]

TASK [test : debug] *****************************************************************************************************
ok: [SW-TEST] => {
    "output": {
        "banners": {},
        "changed": true,
        "commands": [
            "interface GigabitEthernet1/3",
            "switchport private-vlan mapping 10 6000"
        ],
        "failed": false,
        "updates": [
            "interface GigabitEthernet1/3",
            "switchport private-vlan mapping 10 6000"
        ]
    }
}

PLAY RECAP **************************************************************************************************************************
SW-TEST                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

# AFTER

SWITCH#sh run int gigabitEthernet 1/3
Building configuration...

Current configuration : 378 bytes
!
interface GigabitEthernet1/3
 description COLLECTE: COVAGE BPEA [5Gbps] {CN001427}
 switchport trunk encapsulation dot1q
 switchport trunk native vlan 4094
 switchport mode trunk
 mtu 9198
 load-interval 30
 media-type rj45
 negotiation auto
 no keepalive
 no lldp transmit
 no lldp receive
 no cdp enable
 spanning-tree portfast network
 spanning-tree bpdufilter enable
end

# TEST ON DEVICE

SWITCH#conf t
Enter configuration commands, one per line.  End with CNTL/Z.
SWITCH(config)#interface GigabitEthernet1/3
SWITCH(config-if)#switchport private-vlan mapping 10 6000
Command Rejected: invalid VLAN list
```

With this PR : 
```
# Restart Playbook

PLAY [SW-TEST] **********************************************************************************************************************

TASK [test : COMMAND] ***************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SWITCH(config-if)#
fatal: [SW-TEST]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/var/folders/ml/p19wycf153nc0t30ppcshlrh0000gn/T/ansible_ios_config_payload_JjWHPV/ansible_ios_config_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_config.py\", line 577, in <module>\n  File \"/var/folders/ml/p19wycf153nc0t30ppcshlrh0000gn/T/ansible_ios_config_payload_JjWHPV/ansible_ios_config_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_config.py\", line 502, in main\n  File \"/var/folders/ml/p19wycf153nc0t30ppcshlrh0000gn/T/ansible_ios_config_payload_JjWHPV/ansible_ios_config_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_config.py\", line 376, in edit_config_or_macro\n  File \"/var/folders/ml/p19wycf153nc0t30ppcshlrh0000gn/T/ansible_ios_config_payload_JjWHPV/ansible_ios_config_payload.zip/ansible/module_utils/connection.py\", line 195, in __rpc__\nansible.module_utils.connection.ConnectionError: switchport private-vlan mapping 10 6000\r\nCommand Rejected: invalid VLAN list\r\n\r\nSWITCH(config-if)#\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
...ignoring

TASK [test : debug] *****************************************************************************************************
ok: [SW-TEST] => {
    "output": {
        "changed": false,
        "exception": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/var/folders/ml/p19wycf153nc0t30ppcshlrh0000gn/T/ansible_ios_config_payload_JjWHPV/ansible_ios_config_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_config.py\", line 577, in <module>\n  File \"/var/folders/ml/p19wycf153nc0t30ppcshlrh0000gn/T/ansible_ios_config_payload_JjWHPV/ansible_ios_config_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_config.py\", line 502, in main\n  File \"/var/folders/ml/p19wycf153nc0t30ppcshlrh0000gn/T/ansible_ios_config_payload_JjWHPV/ansible_ios_config_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_config.py\", line 376, in edit_config_or_macro\n  File \"/var/folders/ml/p19wycf153nc0t30ppcshlrh0000gn/T/ansible_ios_config_payload_JjWHPV/ansible_ios_config_payload.zip/ansible/module_utils/connection.py\", line 195, in __rpc__\nansible.module_utils.connection.ConnectionError: switchport private-vlan mapping 10 6000\r\nCommand Rejected: invalid VLAN list\r\n\r\nSWITCH(config-if)#\n",
        "failed": true,
        "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/var/folders/ml/p19wycf153nc0t30ppcshlrh0000gn/T/ansible_ios_config_payload_JjWHPV/ansible_ios_config_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_config.py\", line 577, in <module>\n  File \"/var/folders/ml/p19wycf153nc0t30ppcshlrh0000gn/T/ansible_ios_config_payload_JjWHPV/ansible_ios_config_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_config.py\", line 502, in main\n  File \"/var/folders/ml/p19wycf153nc0t30ppcshlrh0000gn/ [...]

2020-12-16 14:06 UTC, NilashishC requested changes
@nidebr Thank you for opening this pull request. It would be really nice if you could add a unit test to cover this scenario as well.

2020-12-18 14:31 UTC, nidebr commented
> @nidebr Thank you for opening this pull request. It would be really nice if you could add a unit test to cover this scenario as well.

I tried to look at your unit tests but I don't know how to test this scenario, because it is a simple search string in the return of IOS Terminal.

If you have an idea, I'm interested, I haven't found an example with the other "stderr".

BR.
Nick

2021-01-05 07:40 UTC, NilashishC commented
@nidebr Alternatively, you can also add an integration test in the [ios_config test suite](https://github.com/ansible-collections/cisco.ios/blob/main/tests/integration/targets/ios_config/tests/cli/defaults.yaml) to test this. Something like the following should do the trick:

```yaml
- name: Validate Terminal Error Regex
  ios_config:
    lines:
      - switchport private-vlan mapping 10 6000
    parents: interface GigabitEthernet0/1
  register: result
  ignore_errors: True

- assert:
    that:
      - result.failed == True
```
Thanks!

2021-01-06 19:37 UTC, justjais commented
@nidebr can you plz update the PR with the suggested change

2021-01-08 17:30 UTC, nidebr commented
> @nidebr can you plz update the PR with the suggested change

Sorry for delay, I make update this WE.

2021-01-13 12:42 UTC, NilashishC commented
recheck

2021-01-13 12:42 UTC, NilashishC approved these changes

2021-01-27 07:10 UTC, merged