Fix logging commands for v12 versions
ansible-collections/cisco.ios pull request #288
Opened 2021-03-26 17:52 UTC by nahun

##### SUMMARY
Fixes #207 

Checks the start of the os_version string for v12 version instead of anywhere in the string. Otherwise it will match versions like 16.12.4.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ios_logging

2021-03-29 06:33 UTC, justjais approved these changes

2021-03-29 06:34 UTC, justjais requested changes
@nahun can u plz add a Unit TC to handle the respective scenario

2021-04-12 08:08 UTC, Andersson007 commented
@nahun can we help with something?

2021-04-12 18:34 UTC, nahun commented
Mostly I just need to find the time to figure out where and how to add the testing.

2021-05-07 11:17 UTC, justjais commented
@nahun u need to add the unit tests for the scenario for which you've changed the implementation here:  https://github.com/ansible-collections/cisco.ios/blob/main/tests/unit/modules/network/ios/test_ios_logging.py#L105

2021-05-14 11:08 UTC, merged