[DNM] check netcommon changes
ansible-collections/cisco.ios pull request #486
Opened 2022-01-18 09:54 UTC by KB-perByte

##### SUMMARY

check netcommon changes

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2022-01-18 09:58 UTC, KB-perByte commented
recheck

2022-01-18 14:27 UTC, Qalthos commented
recheck

2022-01-18 15:10 UTC, KB-perByte commented
recheck

2022-01-31 08:31 UTC, KB-perByte commented
recheck

2022-04-21 13:40 UTC, Qalthos requested changes

2022-04-21 13:40 UTC, Qalthos commented on changelogs/fragments/netcommon_ref_update.yaml
> +  - "Minimum required ansible.netcommon version is 2.5.0."
```suggestion
  - "Minimum required ansible.netcommon version is 2.5.1."
```
I don't see this enforced?

2022-04-25 13:19 UTC, Qalthos approved these changes

2022-04-26 06:51 UTC, merged