Fix bgp_global errors.
ansible-collections/cisco.ios pull request #498
Opened 2022-01-28 22:33 UTC by dalrrard

##### SUMMARY
Fix bgp_global error when peer-groups are defined.
The bgp_global module could only collect facts for ipv4 addresses.
Added the ability to work with ipv6 addresses and peer-groups.

Fix issue with peer-group neighbors not being found.

Fix #318 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
bgp_global

##### ADDITIONAL INFORMATION
The module would only accept IPv4 addresses as neighbors even though IPv6 addresses and peer-groups were defined in the argspec. Added path for all 3 to be created, and in the case of a peer-group, make sure that we define it in the config before using it in a neighbor.

2022-02-02 09:57 UTC, KB-perByte requested changes

2022-02-02 09:57 UTC, KB-perByte commented on plugins/module_utils/network/ios/argspec/bgp_global/bgp_global.py
> +                    "mutually_exclusive": [
Ansible won't recognize the `mutually_exclusive` key here as it is intended to work, rather it is recommended to use `choice` to handle the same. This is supposed to break parts of the execution.

2022-02-07 08:41 UTC, KB-perByte commented
Hey @dalrrard, the bgp_global module is being considered for fresh code optimization. with some requested features and changes for the upcoming major release, We may consider the tagged issue with that. We might close this PR for the same.
Regards

2022-02-09 20:23 UTC, dalrrard commented
No worries. I had a few more PRs coming in after this for that module for various things anyway. You're good to close this out if you want.

2022-03-07 13:27 UTC, KB-perByte commented
Hey @dalrrard, closing this issue as most of the `bgp_global` related issues are collectively addressed in https://github.com/ansible-collections/cisco.ios/pull/513, you may check the PR and add any suggestion you have.
Regards

2022-03-07 13:27 UTC, closed without merging