Prep release 3.3.2
ansible-collections/cisco.ios pull request #661
Opened 2022-09-23 17:14 UTC by KB-perByte

2022-09-23 17:18 UTC, Qalthos approved these changes

2022-09-23 17:41 UTC, Qalthos requested changes
I'm assuming the quote cleanup, reordering, and realigning of text was done automatically, so I'm just going to ignore most of that

2022-09-23 17:41 UTC, Qalthos commented on changelogs/changelog.yaml
> -      - acls_bugfix_and_option_deprication.yaml
ditto

2022-09-24 06:37 UTC, KB-perByte commented on changelogs/changelog.yaml
> +        - Please refer to ansible.netcommon changelog (https://github.com/ansible-collections/ansible.netcommon/blob/main/changelogs/CHANGELOG.rst#ansible-netcommon-collection-release-notes)
```suggestion
        - Please refer to ansible.netcommon `changelog <https://github.com/ansible-collections/ansible.netcommon/blob/main/changelogs/CHANGELOG.rst#ansible-netcommon-collection-release-notes>`_
```

2022-09-24 06:38 UTC, KB-perByte commented on changelogs/changelog.yaml
> +      - ios_l3_interfaces_module_rm_implementation.yaml
```suggestion
      - ios_l3_interfaces_module_rm_implimentation.yaml
```

2022-09-24 06:38 UTC, KB-perByte commented on changelogs/changelog.yaml
> +      - acls_bugfix_and_option_depreciation.yaml
```suggestion
      - acls_bugfix_and_option_deprication.yaml
```

2022-09-24 06:51 UTC, merged