[WIP] fix acls
ansible-collections/cisco.ios pull request #696
Opened 2022-11-30 12:57 UTC by KB-perByte

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2022-12-02 10:01 UTC, ashwini-mhatre reviewed
could you please add some tests

2022-12-02 14:51 UTC, Qalthos requested changes

2022-12-02 14:51 UTC, Qalthos commented on plugins/module_utils/network/ios/config/acls/acls.py
> +                self.commands[begin : len(self.commands)],
I think this is the solution to the sanity issue.
```suggestion
            self.commands[begin:len(self.commands)] = rearrange_cmds(
                self.commands[begin:len(self.commands)],
```

2022-12-02 14:56 UTC, Qalthos commented on plugins/module_utils/network/ios/config/acls/acls.py
> +                self.commands[begin : len(self.commands)],
Ugh yeah, black is the one introducing this change. We will have to do something about that.

2022-12-02 15:01 UTC, Qalthos commented on plugins/module_utils/network/ios/config/acls/acls.py
> +                self.commands[begin : len(self.commands)],
Is `len(self.commands)` meant to change over the course of execution? Can we not instead do something like this?
```suggestion
            end = len(self.commands)
            self.commands[begin:end] = rearrange_cmds(
                self.commands[begin:],
```

2022-12-09 09:55 UTC, rohitthakur2590 approved these changes

2022-12-09 10:12 UTC, merged