ios_snmp_server: improvment for snmp-server module
ansible-collections/cisco.ios pull request #809
Opened 2023-04-21 21:55 UTC by earendilfr

- add the possibility manage the match part of the context for snmp-server group this part could be usefull on cisco devices to retrieve the MAC table of all VLANs with SNMPv3

- Fixe an issue with snmp-server ifindex: the command working fine but the result in command could be also seen with the command `snmp ifmib ifindex persist`

##### SUMMARY
Performing two change in ios_snmp_server module:
- Add the possibility to manage the `match` part for `context` in `snmp-server group` command
- I have also seen a weird bug with the if_index parameter:
  the parameter is correctly sent to the switch but, on many switches, we should also check the command `snmp ifmib ifindex persist`to validate if the command is present

##### ISSUE TYPE

- Bugfix Pull Request
- Feature Pull Request

##### COMPONENT NAME
ios_snmp_server

##### ADDITIONAL INFORMATION

Before add the context match
```
snmp-server group group1 v3 auth context vlan-
```

After:
```
snmp-server group group1 v3 auth
snmp-server group group1 v3 auth context vlan match prefix
```

And the output of the complete commands on Cisco switches
```
fhv-pry-msw01#sh run | section ^snmp
snmp-server group group1 v3 auth
snmp-server group group1 v3 auth context vlan- match prefix
snmp-server location nowhere
snmp-server contact noreply@example.org
snmp-server enable traps license
snmp-server enable traps stackwise
snmp-server enable traps envmon fan shutdown supply status
snmp ifmib ifindex persist
```

and the result for the gathered output:
```
        "gathered": {
            "contact": "noreply@example.org",
            "groups": [
                {
                    "group": "group1",
                    "read": "snmp-view-full",
                    "version": "v3",
                    "version_option": "auth"
                },
                {
                    "context": "vlan-",
                    "group": "group1",
                    "match": "prefix",
                    "version": "v3",
                    "version_option": "auth"
                }
            ],
            "if_index": true,
            "location": "nowhere",
            "views": [
                {
                    "family_name": "iso",
                    "included": true,
                    "name": "snmp-view-full"
                }
            ]
        }
```

2023-04-27 09:37 UTC, KB-perByte requested changes

2023-04-27 09:37 UTC, KB-perByte commented on changelogs/fragments/ios_snmp_server_doc_changes.yml
> +doc_changes:
```suggestion
minor_changes:
```

2023-05-03 06:16 UTC, KB-perByte commented
@roverflow cc

2023-05-09 14:34 UTC, earendilfr commented on plugins/module_utils/network/ios/rm_templates/snmp_server.py
> +                ^snmp(-server|\sifmib)\sifindex
I have tried to add some entry related to the ifindex part in unit test file

2023-11-24 11:30 UTC, roverflow requested changes
Hey @earendilfr , thanks for the contribution, if you are still looking to merge this PR, can you resolve the conflicts and also can you add tests for the match attribute that you have added

2023-11-24 15:43 UTC, earendilfr commented
I'm nearly sure that this PR is already covered with the PR #828.
So we can close it

2023-11-24 15:43 UTC, closed without merging