Added SNMPv3 user to render in output
ansible-collections/cisco.ios pull request #810
Opened 2023-04-24 08:39 UTC by roverflow

##### SUMMARY
This pull request addresses an issue where SNMPv3 user configuration was not being displayed in the running-config. The fix involves adding a new command to retrieve the output and parse it to add it to the facts list

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME

- plugins/module_utils/network/ios/facts/snmp_server/snmp_server.py

2023-04-24 08:45 UTC, KB-perByte commented
Let's add some unit tests to this change!

2023-04-24 08:46 UTC, KB-perByte commented
@roverflow if you could also update the examples as per https://github.com/ansible-collections/cisco.ios/pull/786
it would be helpful! 
Regards

2023-04-25 09:06 UTC, KB-perByte commented on tests/unit/modules/network/ios/test_ios_snmp_server.py
>      def test_ios_snmp_server_merged_idempotent(self):
Please add tests for action states

2023-04-25 09:07 UTC, KB-perByte commented on changelogs/fragments/snmpv3_user_render.yml
> +  - SNMPv3 user rendering now works correctly.
A bit more descriptive here!

2023-04-25 09:08 UTC, KB-perByte commented on plugins/module_utils/network/ios/facts/snmp_server/snmp_server.py
> +    def get_snmpv3_user_facts(self, snmpv3_user):
As this, is not a trivial resource module way, can we add some docstrings and comment to the code for us to reference it better later

2023-04-25 09:10 UTC, KB-perByte commented on plugins/module_utils/network/ios/facts/snmp_server/snmp_server.py
> +    def get_snmpv3_user_facts(self, snmpv3_user):
Add a note to the user attribute in docs to state that the behavior is supposed to impact idempotency.

2023-05-02 05:28 UTC, KB-perByte requested changes

2023-05-02 05:28 UTC, KB-perByte commented on plugins/module_utils/network/ios/facts/snmp_server/snmp_server.py
> +        if len(snmp_user_data) != 0:
this condition can be simplified

2023-05-02 05:28 UTC, KB-perByte commented on changelogs/fragments/snmpv3_user_render.yml
> +  - Adding SNMPv3 user config data using different command in addition to running-config.
this needs to be corrected

2023-05-02 07:18 UTC, KB-perByte commented on plugins/module_utils/network/ios/facts/snmp_server/snmp_server.py
> +        if len(snmp_user_data):
len() is also not required

2023-05-02 07:29 UTC, roverflow commented on plugins/module_utils/network/ios/facts/snmp_server/snmp_server.py
> +        if len(snmp_user_data):
Got it!

2023-05-02 10:40 UTC, KB-perByte commented on changelogs/fragments/snmpv3_user_render.yml
> +  - snmp_server - updated module to get snmpv3 user data from different command.
```suggestion
  - snmp_server - update module to get snmp_server user configuration.
```

2023-05-02 10:40 UTC, KB-perByte approved these changes

2023-06-06 08:13 UTC, merged